// Generated by scripts/generate-font-metric-fallbacks.mjs — do not edit.
// Regenerate with: npm run generate-font-fallbacks

// Metric-matched fallback @font-face rules, keyed by web font family name.
export const metricFallbackFaces: Record<string, string> = {
  "Lora": "@font-face {\n  font-family: 'Lora Fallback';\n  src: local('Georgia');\n  size-adjust: 104.980%;\n  ascent-override: 95.828%;\n  descent-override: 26.100%;\n  line-gap-override: 0.000%;\n}",
  "Atkinson Hyperlegible Next": "@font-face {\n  font-family: 'Atkinson Hyperlegible Next Fallback';\n  src: local('Arial');\n  size-adjust: 99.596%;\n  ascent-override: 98.799%;\n  descent-override: 31.728%;\n  line-gap-override: 0.000%;\n}",
  "Sometype Mono": "@font-face {\n  font-family: 'Sometype Mono Fallback';\n  src: local('Courier New');\n  size-adjust: 96.651%;\n  ascent-override: 95.705%;\n  descent-override: 28.453%;\n  line-gap-override: 0.000%;\n}",
  "Montserrat": "@font-face {\n  font-family: 'Montserrat Fallback';\n  src: local('Arial');\n  size-adjust: 112.831%;\n  ascent-override: 85.792%;\n  descent-override: 22.246%;\n  line-gap-override: 0.000%;\n}",
  "Source Sans 3": "@font-face {\n  font-family: 'Source Sans 3 Fallback';\n  src: local('Arial');\n  size-adjust: 93.764%;\n  ascent-override: 109.211%;\n  descent-override: 42.660%;\n  line-gap-override: 0.000%;\n}",
};
